M48
; DRILL file KiCad 10.0.4 date 2026-08-31T15:07:02
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-08-31T15:07:02-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0402
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1732
%
G90
G05
T1
X6.9299Y-3.4482
X6.9299Y-4.1758
T2
X6.85Y-3.212
X6.85Y-4.412
M30
